# Generated by Django 4.2.15 on 2025-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
