# Generated by Django 4.2.15 on 2025-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_company_customuser_custom_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
