# Generated by Django 4.2.15 on 2025-05-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0002_company_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
