# Generated by Django 4.2.15 on 2025-05-13 19:50

import apps.company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Formato permitido: jpg, jpeg, png, webp. Tamaño máximo: 2MB",
                null=True,
                upload_to=apps.company.models.company_logo_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
