# Generated by Django 4.2.15 on 2025-05-13 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
